"""
Build the VENDOR copy of the catalog: the exact same master as
build_reference.py, but encrypted under a SEPARATE vendor password and written
to assets/reference.vendor.enc.js (window.LABEL_ENC_VENDOR).

The vendor sub-portal (vendor.html) decrypts this with the vendor password only.
Because it is a distinct file + key, vendor access is revoked/rotated on its own
(rebuild with a new --vendor-password) without touching the team's catalog.

    python3 tools/build_vendor_reference.py --vendor-password "the vendor password"

Run it right after build_reference.py so the two stay in lock-step.
"""
import os
import json
import base64
import argparse

from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from build_reference import build_master, ITERS, HERE   # reuse the identical master

OUT = os.path.join(HERE, "..", "assets", "reference.vendor.enc.js")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vendor-password", default=os.environ.get("VENDOR_PASSWORD", ""))
    args = ap.parse_args()
    if not args.vendor_password:
        raise SystemExit("Provide the vendor password via --vendor-password or VENDOR_PASSWORD env var.")

    master = build_master()
    plaintext = json.dumps(master, ensure_ascii=False, separators=(",", ":")).encode("utf-8")

    salt, iv = os.urandom(16), os.urandom(12)
    key = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=salt, iterations=ITERS).derive(
        args.vendor_password.encode("utf-8"))
    ct = AESGCM(key).encrypt(iv, plaintext, None)

    enc = {"v": 1, "iters": ITERS,
           "salt": base64.b64encode(salt).decode(),
           "iv": base64.b64encode(iv).decode(),
           "ct": base64.b64encode(ct).decode()}
    with open(OUT, "w", encoding="utf-8") as out:
        out.write("// Encrypted VENDOR catalog — generated by tools/build_vendor_reference.py.\n")
        out.write("// Public ciphertext; unreadable without the VENDOR password.\n")
        out.write("window.LABEL_ENC_VENDOR = ")
        json.dump(enc, out, separators=(",", ":"))
        out.write(";\n")
    print(f"Wrote {OUT}")
    print(f"  {master['meta']['count']} SKUs (vendor-encrypted, AES-256-GCM, PBKDF2 {ITERS})")


if __name__ == "__main__":
    main()
